# Database table/layer names used by validation and map loading.
tables.sqlite.measurement=measurement

# GeoPackage layers
tables.geopackage.basin=basin
tables.geopackage.network=network

# Prefixes
tables.geopackage.topology.prefix=topology
tables.geopackage.simulation.prefix=sim
